name: discord-tunnel

version: "3.8"

services:
    # https://github.com/FlorianLeChat/Discord-Tunnel
    java:
        image: discord-tunnel
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            retries: 3
            timeout: 5s
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G
                reservations:
                    cpus: "0.25"
                    memory: 256M
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080